// Generated by Selenium IDE
/*
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System;
[TestFixture]
public class UntitledTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    public string waitForWindow(int timeout)
    {
        try
        {
            Thread.Sleep(timeout);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count)
        {
            return whNow.Except(whThen).First().ToString();
        }
        else
        {
            return whNow.First().ToString();
        }
    }
    public static void RightClick(IWebDriver driver, IWebElement element)
    {
        Actions builder = new Actions(driver);
        builder.ContextClick(element).Perform();
    }
    [Test]
    public void untitled()
    {
        driver.Navigate().GoToUrl("https://retaillink.login.wal-mart.com/?ServerType=IIS1&CTAuthMode=BASIC&language=en&utm_source=retaillink&utm_medium=redirect&utm_campaign=FalconRelease&CT_ORIG_URL=/&ct_orig_uri=/");
        driver.Manage().Window.Size = new System.Drawing.Size(720, 707);
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(1) .input-field-wrapper__inputFieldAuto___2ML5s > .form-control__formControl___3uDUX")).Click();
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(1) .input-field-wrapper__inputFieldAuto___2ML5s > .form-control__formControl___3uDUX")).SendKeys("Cop1488");
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(2) .form-control__formControl___3uDUX")).Click();
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(2) .form-control__formControl___3uDUX")).SendKeys("Nuevo21");
        driver.FindElement(By.CssSelector(".app-btn")).Click();
        Thread.Sleep(9000);
        driver.FindElement(By.LinkText("Favoritos")).Click();
        driver.FindElement(By.LinkText("Soporte de Decisión - Nuevo")).Click();
        driver.FindElement(By.CssSelector(".dropdown:nth-child(7) .caret")).Click();
        driver.FindElement(By.LinkText("Soporte de Decisión - Nuevo")).Click();
        //driver.FindElement(By.LinkText("Soporte de Decisión - Nuevo")).Click();
        //driver.FindElement(By.LinkText("Soporte de Decisión - Nuevo")).Click();
        driver.FindElement(By.LinkText("Mis Reportes")).Click();
        Thread.Sleep(10000);
        driver.SwitchTo().Frame(2);
        driver.FindElement(By.Id("btnShwSearch")).Click();
        driver.FindElement(By.Id("searchtxt")).Click();
        driver.FindElement(By.Id("searchtxt")).SendKeys("GL VTA COPY");
        driver.FindElement(By.Id("btnSearchReport")).Click();
        Thread.Sleep(10000);
        vars["WindowHandles"] = driver.WindowHandles;
        //RightClick(driver, documento);
        IWebElement documento = driver.FindElement(By.Id("SD39499112"));
        Thread.Sleep(5000);
        RightClick(driver, documento);
        driver.FindElement(By.LinkText("Modificar")).Click();
        //driver.FindElement(By.LinkText("Modificar")).Click();
        //driver.FindElement(By.LinkText("Modificar")).Click();
        vars["win8974"] = waitForWindow(2000);
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["win8974"].ToString());
        driver.SwitchTo().Frame(1);
        */

        /*driver.FindElement(By.Id("step4a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(5);
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("F1000010")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(2);
        driver.SwitchTo().Frame(0);
        FindElement(By.LinkText("Fecha Pos. (mm/dd/yyyy)")).Click();
        driver.FindElement(By.Id("204F1000010")).Click();
        driver.FindElement(By.Id("204F1000010")).Click();
        driver.FindElement(By.Id("204F1000010")).Click();
        {
            var element = driver.FindElement(By.Id("204F1000010"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }*/

        /*driver.SwitchTo().Window(driver.WindowHandles.Last());
        driver.SwitchTo().ParentFrame();
        driver.SwitchTo().Frame(7);
        driver.FindElement(By.Id("rdoTransExcelFile2")).Click();
        */
        /*-----------------------------------------------------------------------------------------
        driver.FindElement(By.Id("step4a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(5);
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("F1000010")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(2);
        driver.SwitchTo().Frame(0);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("204F1000010")).Click();
        driver.FindElement(By.Id("204F1000010")).Click();
        {
            var element = driver.FindElement(By.Id("204F1000010"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }


        driver.FindElement(By.Id("step4a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(5);
        driver.SwitchTo().Frame(1);
        //Thread.Sleep(6000);
        driver.FindElement(By.Id("F1000010")).Click();
        Thread.Sleep(1000);
        //driver.SwitchTo().DefaultContent();
        //Thread.Sleep(1000);
        driver.SwitchTo().DefaultContent();
        Thread.Sleep(1000);
        IWebElement frameDate = driver.FindElement(By.Id("F1000010_frame"));
        driver.SwitchTo().Frame(frameDate);
        */
        //driver.SwitchTo().ParentFrame();
        //driver.SwitchTo().Frame(2);
        //driver.SwitchTo().Frame(0);
        //driver.SwitchTo().DefaultContent();
        //var frames = driver.FindElements(By.TagName("iframe"));
        //var frameSize = driver.FindElements(By.TagName("iframe"));
        //Console.Write(frameSize);
        //driver.SwitchTo().Frame(driver.FindElement(By.Id("mid")));
        //driver.SwitchTo().Frame(driver.FindElement(By.XPath("//*[@id='204F1000010']")));
        //int frameSize = driver.FindElements(By.TagName("iframe"));
        //Console.Write(frames);
        //System.out.println(frameSize);

        //driver.SwitchTo().Frame(2);
        //driver.SwitchTo().Frame(0);
        //Thread.Sleep(6000);
        //driver.FindElement(By.LinkText("Fecha Pos. (mm/dd/yyyy)")).Click();
        /*------------------------------------------------------------------------------------
        driver.FindElement(By.Id("204F1000010")).Click(); //204F1000010 204F1000010
        driver.FindElement(By.Id("204F1000010")).Click();// F1000010_frame
        driver.FindElement(By.Id("204F1000010")).Click();
        {
            var element = driver.FindElement(By.Id("204F1000010"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }*/
        /*
        driver.FindElement(By.Id("204comma8F1000010")).Click();
        driver.FindElement(By.Id("204comma8F1000010")).Click();*//*-----------------------------------------------
        {
            var element = driver.FindElement(By.Id("204comma8F1000010"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(3);
        driver.FindElement(By.Id("firstValue")).Click();
        driver.FindElement(By.Id("firstValue")).SendKeys("01-01-2020");
        driver.FindElement(By.Id("lastValue")).Click();
        driver.FindElement(By.Id("lastValue")).SendKeys("31-01-2020");
        driver.FindElement(By.Id("btnAnd")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("step6a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(7);
        driver.FindElement(By.Id("rdoTransExcelFile2")).Click();
        driver.FindElement(By.Id("subnow")).Click();
        driver.Close();
        driver.SwitchTo().Window(vars["root"].ToString());
        driver.FindElement(By.LinkText("Estado")).Click();
        driver.SwitchTo().Frame(2);
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector("tr:nth-child(2) input")).Click();
        vars["WindowHandles"] = driver.WindowHandles;
        driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2) > .status_table")).Click();
        vars["win9865"] = waitForWindow(2000);
        driver.SwitchTo().Window(vars["win9865"].ToString());
        driver.Close();
        driver.SwitchTo().Window(vars["root"].ToString());
        {
            var element = driver.FindElement(By.LinkText("Desconectar"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.LinkText("Desconectar"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.LinkText("Desconectar"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.LinkText("Desconectar")).Click();
        driver.Close();
    }
}
*/

// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    public string waitForWindow(int timeout)
    {
        try
        {
            Thread.Sleep(timeout);
        }
        catch (Exception e)
        {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count)
        {
            return whNow.Except(whThen).First().ToString();
        }
        else
        {
            return whNow.First().ToString();
        }
    }
    public static void RightClick(IWebDriver driver, IWebElement element)
    {
        Actions builder = new Actions(driver);
        builder.ContextClick(element).Perform();
    }
    [Test]
    public void wALMARTGENERA()
    {
         //driver.Navigate().GoToUrl("https://retaillink.wal-mart.com/new_home/");
        driver.Navigate().GoToUrl("https://retaillink.login.wal-mart.com/?ServerType=IIS1&CTAuthMode=BASIC&language=en&utm_source=retaillink&utm_medium=redirect&utm_campaign=FalconRelease&CT_ORIG_URL=/&ct_orig_uri=/");
        driver.Manage().Window.Size = new System.Drawing.Size(720, 707);
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(1) .input-field-wrapper__inputFieldAuto___2ML5s > .form-control__formControl___3uDUX")).Click();
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(1) .input-field-wrapper__inputFieldAuto___2ML5s > .form-control__formControl___3uDUX")).SendKeys("Cop1488");
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(2) .form-control__formControl___3uDUX")).Click();
        driver.FindElement(By.CssSelector(".input-field-wrapper__inputFieldWrapper___3syAG:nth-child(2) .form-control__formControl___3uDUX")).SendKeys("Nuevo21");
        driver.FindElement(By.CssSelector(".app-btn")).Click();
        Thread.Sleep(9000);
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".favorite > a")).Click();
        driver.FindElement(By.LinkText("Mis Reportes")).Click();
        driver.SwitchTo().Frame(2);
        driver.FindElement(By.Id("btnShwSearch")).Click();
        driver.FindElement(By.Id("searchtxt")).Click();
        driver.FindElement(By.Id("searchtxt")).SendKeys("GL VTA COPY");
        driver.FindElement(By.Id("btnSearchReport")).Click();
        {
            var element = driver.FindElement(By.Id("btnRefresh"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        vars["WindowHandles"] = driver.WindowHandles;
        IWebElement documento = driver.FindElement(By.Id("SD39499112"));
        RightClick(driver, documento);
        driver.FindElement(By.LinkText("Modificar")).Click();
        //driver.FindElement(By.LinkText("Modificar")).Click();
        vars["win8396"] = waitForWindow(2000);
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["win8396"].ToString());
        driver.SwitchTo().Frame(7);
        driver.FindElement(By.Id("rdoTransExcelFile2")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("step4a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(5);
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("F1000010")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(2);
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.Id("204F1000010")).Click();
        driver.FindElement(By.Id("204F1000010")).Click();
        {
            var element = driver.FindElement(By.Id("204F1000010"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("204comma8F1000010")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(3);
        driver.FindElement(By.Id("firstValue")).Click();
        driver.FindElement(By.Id("firstValue")).Click();
        driver.FindElement(By.Id("firstValue")).SendKeys("01-01-2020");
        driver.FindElement(By.Id("lastValue")).Click();
        driver.FindElement(By.Id("lastValue")).SendKeys("01-30-2020");
        driver.FindElement(By.Id("btnAnd")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(1);
        driver.FindElement(By.Id("step6a")).Click();
        driver.SwitchTo().DefaultContent();
        driver.SwitchTo().Frame(7);
        driver.FindElement(By.Id("subnow")).Click();
        driver.Close();
        driver.SwitchTo().Window(vars["root"].ToString());
    }
}
